# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f66585e8a97937639a58c603dd531a015c0f83e3b0cf5471db2e8b106e87cbcfe68fcde214cd54c8c770f9ac611adfde018c3a91df8fe9fb5c8a2f2ae8a637a

test:
  secret_key_base: fab3895c57accee4a17ad5de04f0000bbdef59b8e352e3203b2d565cf33fb05cdd027a0c95accfe79313bc47c78a44676109c1ec914727437cbac47d59e35dc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
